version: '2'
 
services:  
  consul:
    container_name: consul.server
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1
    image: consul:latest
    volumes:
      - ./consul/config:/consul/config
    ports:
      - "9300:9300"
      - "9500:9500"
      - "9600:9600/udp"
  
  vault:
    container_name: vault.server
    image: vault
    ports:
      - "9200:8200"
    volumes:
      - ./vault/config:/mnt/vault/config
      - ./vault/data:/mnt/vault/data
      - ./vault/logs:/mnt/vault/logs
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"${LOCAL_IP}:9500","advertise_addr":"http://${LOCAL_IP}", "path":"vault/"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}}}
    command: server
