server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/progak/MicroServiceSample.git
          search-paths:
            - config-repo

management:
  security:
    enabled: false